### ISSUE TITLE
time-grunt makes grunt slow while not running any task

### ISSUE THREAD

**Issue by oosterholt** [sindresorhus/time-grunt#28]
time-grunt makes running of grunt very slow when not running tasks.
E.g. 

```
grunt --verbose --version 
```

I noticed this because "grunt bash completion" uses exact that command.

**Comment by mgiorgino** [comment]
This issue seems to still be present.
With a simple test case, on windows and linux:
node -v  ## v4.4.5
npm -v  ## 3.9.2

`Gruntfile.js`:
```
module.exports = (grunt) => {
  require('time-grunt')(grunt);
  grunt.initConfig();
};
```
`package.json`:
```
{
  "author": "Me",
  "name": "testTimeGrunt",
  "version": "1.0.0",
  "devDependencies": {
    "grunt": "1.0.1",
    "time-grunt": "1.3.0"
  },
  "dependencies": {}
}
```

Then simply run:
```
npm install
grunt -version -v
```
And wait forever...

Strangely, a workaround is to use:
```
grunt -V -v
```
