### ISSUE TITLE
Miscalculation of task title length

### ISSUE THREAD

**Issue by pkollitsch** [sindresorhus/time-grunt#36]
there seems to be a little miscalculation in the part that shortens executed task titles in the summary:.

eg. 

```
Execution Time (2014-03-21 11:06:16 UTC)
loading tasks        2.9s  ▇ 5%
copy:verb           12.9s  ▇▇▇▇ 21%
compass:...ckicons  21.4s  ▇▇▇▇▇▇ 35%
compass:...awesome   1.3s  ▇ 2%
compass:bootstrap    4.1s  ▇▇ 7%
compass:theme       750ms  ▇ 1%
autopref...r:style   1.8s  ▇ 3%
cssmin:global          1s  ▇ 2%
modernizr:dist        11s  ▇▇▇▇ 18%
uglify:h...rscript   3.5s  ▇ 6%
```

task 3 is "compass:stackicons" and could be written out (sta instead ...)
task 7 is "autoprefixer:style" and could be written out (ixe instead ...)

not sure if that is regarded as by design or a bug.

**Comment by slinto** [comment]
I tested this issue, but I think it's actually fixed. It's there any problem with shortening?

**Comment by sindresorhus** [comment]
Closing as this project is deprecated because Grunt is no longer actively maintained, so it doesn't make sense for me to maintain this project either.
