### ISSUE TITLE
Support for grunt watch?

### ISSUE THREAD

**Issue by peol** [sindresorhus/time-grunt#4]
It would be cool to support when tasks are being run in grunt-watch (becuase you can easily remove to default output from watch with the `dateFormat` option in grunt-watch). I might take a swing at it next week but I wanted to file a bug so I don't forget :)

**Comment by sindresorhus** [comment]
Closing as this project is deprecated because Grunt is no longer actively maintained, so it doesn't make sense for me to maintain this project either.
