### ISSUE TITLE
Log with ambiguous-width characters

### ISSUE THREAD

**Issue by tgfjt** [sindresorhus/time-grunt#52]
Hi.

I have a issue about Logging for Execution Time.

I'm using Max OSX with iTerm2 `Build 2.0.0.20141103`

and my setting with iTerm2 below:

✓ Treat ambiguous-width characters as double width

`require('figures').square`: `▇` This chars is ambiguous-width chars.

What do you think about using another chars like `require('figures').squareSmallFilled`?

### square (not as double width)

![2014-12-03 22 26 54](https://cloud.githubusercontent.com/assets/2628239/5280996/ba4943f8-7b3b-11e4-95ae-f73fefcf5958.png)

### square (as double width)

![2014-12-03 22 27 11](https://cloud.githubusercontent.com/assets/2628239/5280997/ba4cce92-7b3b-11e4-90a0-98be0addf05a.png)

### squareSmallFilled (as double width)

![2014-12-03 22 27 54](https://cloud.githubusercontent.com/assets/2628239/5280998/ba4e4b32-7b3b-11e4-9ac2-2fbcb84e29c6.png)

**Comment by eddiemonge** [comment]
or go pure old school with `|`: 

`1.5s ||||||||||||||||||||||||||||||||||||||| 100%`

**Comment by slinto** [comment]
I think it's actually OK and we can close this. But if someone has a problem currently, please write here and we will try to resolve it.
