### ISSUE TITLE
Changing output color

### ISSUE THREAD

**Issue by Deklin** [sindresorhus/time-grunt#57]
The color in your screenshot is perfect, however for us using gitbash the color is a dark blue and unreadable. Is there a way to change the color? we are using 1.0.0

**Comment by sindresorhus** [comment]
Nope. But if you use 1.1.0 you'll get a new version of chalk which should work around the blue color issue on Windows terminals.

**Comment by Deklin** [comment]
Noticed that, its good enough:) Thanks!
