### ISSUE TITLE
Divide by zero error if totalTime == 0

### ISSUE THREAD

**Issue by spbolton** [sindresorhus/time-grunt#58]
At (Line 109)[https://github.com/sindresorhus/time-grunt/blob/master/index.js#L109] add isNaN check.

			if (isNaN(avg) ||  (avg < 0.01 && !grunt.option('verbose'))) {
				return;
			}

**Comment by spbolton** [comment]
Issue is caused by time less that about 15ms Date.now() is not more accurate than this and anything quicker will return the same value for the end and start time producing a totalTime of 0. process.hrtime() could be used instead of Date.now() for more accurate timings.  NaN causes following error to be displayed.

    e:\git\cloud-commons\pom-main-node-parent\node_modules\time-grunt\index.js:103
                        var bar = new Array(barLength).join(barChar);
                                  ^
    RangeError: Invalid array length
        at createBar (e:\git\cloud-commons\pom-main-node-parent\node_modules\time-grunt\index.js:103:14)

**Comment by sindresorhus** [comment]
> process.hrtime() could be used instead of Date.now() for more accurate timings.

Pull request welcome :)
