### ISSUE TITLE
Execution start time is always in UTC

### ISSUE THREAD

**Issue by isupersid** [sindresorhus/time-grunt#63]
The execution start time is always in UTC. Was looking in the code and it would be great if we can add support to show the time in current timezone. Its really helpful when you are running builds in multiple windows or trying to figure out when you built the last time.

**Comment by sindresorhus** [comment]
The reason it's UTC is that a lot of people are running it on build servers around the world and need an absolute time no matter where it is.

**Comment by isupersid** [comment]
sure, but adding a config setting to switch to displaying time in current timezone would be really useful.

**Comment by sindresorhus** [comment]
Not really interested in adding an option for something that obscure. I'd rather either go with the current way or switch to showing local time with the timezone. Not sure which yet.

**Comment by PombaM** [comment]
I would love to be able to switch time zone!

+1

**Comment by p2media** [comment]
This would be awesome! +1

**Comment by AdrianoCahete** [comment]
:+1:

**Comment by kyanite** [comment]
I also would love to be able to show time based on time zone

**Comment by sindresorhus** [comment]
Let's go with local time and append the timezone. Best of both worlds.
