### ISSUE TITLE
Feature request: Ignore Tasks

### ISSUE THREAD

**Issue by AntonTrapp** [sindresorhus/time-grunt#64]
A way to ignore some tasks would be great. For example: The "watch" tasks takes hours to complete (because it is just waiting) and measuring the time there makes no sense.

**Comment by sindresorhus** [comment]
Duplicate of #51. PR welcome :)

**Comment by AntonTrapp** [comment]
Sorry, missed that. I am afraid that my grunt knowledge is much to low :(

**Comment by AdrianoCahete** [comment]
#51 Just ignore `watch` task, not a list of tasks. 

A way to ignore some other tasks will be good too (notify task, for example).
