### ISSUE TITLE
allow custom barChar character, or non utf8 option

### ISSUE THREAD

**Issue by mattkime** [sindresorhus/time-grunt#65]
not all logging environments support utf8 which can result in - � instead of ▇

it would be nice to replace it with the line character in 'figure', assuming its a ASCII char.

unfortunately its not clear how i might pass config option to grunt-time. might be obvious after a little digging.

this would also address this issue - https://github.com/sindresorhus/time-grunt/issues/52

**Comment by sindresorhus** [comment]
> not all logging environments support utf8

What kind of logging environment doesn't support UTF-8 in 2015?

**Comment by kevva** [comment]
Probably something Windows.

**Comment by mattkime** [comment]
nope, linux. digging up more info from coworkers about why this is the case.

**Comment by slinto** [comment]
I think we can close this. But if someone has a problem currently, please write here and we will try to resolve it.
