### ISSUE TITLE
[feature] Allow depth configuration or whitelist

### ISSUE THREAD

**Issue by Wardormeur** [sindresorhus/time-grunt#71]
In order to be able to see how much it takes for subtask which are regrouped for "lisibility"/"usage" while still having the end-report, having a whitelist or a depth configuration would be nice :)

**Comment by sindresorhus** [comment]
No idea what you're asking. Can you try to be more explicit? Maybe show some examples of how it would work.

**Comment by Wardormeur** [comment]
Consider grunt-contrib-copy with multiple target, that are registred under an alias "copy:all". 
In your grunt build, you'll certainly use copy:all instead of [copy:target1, copy:target2]
Except if I'm wrong, the output will be copy:all xm ys => n%, whereas I'd be interested in the result from copy:target1 as well as copy:target2 while still using copy:all

**Comment by sindresorhus** [comment]
Not something I'm interested in. Consider this module pretty much locked unless something really enticing comes up. I would recommend forking and implementing whatever you want in your fork ;)

**Comment by Wardormeur** [comment]
Roger that, thanks for the quick answer :)
