### ISSUE TITLE
Execution time (date+time) is wrong

### ISSUE THREAD

**Issue by vaff** [sindresorhus/time-grunt#74]
I'm running CET and it shows UTC

![screen shot 2015-12-22 at 13 32 47](https://cloud.githubusercontent.com/assets/351447/11955237/8ead89d6-a8b0-11e5-9416-5f02cd8de095.png)

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/time-grunt/issues/63.
