### ISSUE TITLE
--no-color flag does nothing

### ISSUE THREAD

**Issue by fiznool** [sindresorhus/time-grunt#76]
When running `grunt` with the `--no-color` flag, colors are still produced from this plugin.

**Comment by slinto** [comment]
Hi,
for me, it's ok. I can't see colors. (Running: OSX 10.11.4 + Terminal)

What is your OS please?

**Comment by fiznool** [comment]
Ubuntu 15.10 with guake terminal.

**Comment by slinto** [comment]
I tested it in Ubuntu 15.10 with Quake terminal and everythink is OK. Colors with --no-color flag is not show.
