### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/time-grunt#78]
I don't have the time to maintain this anymore. Luckily it's very stable, so it won't be deprecated or anything like that. However, there are some minor issues that could use fixing and there might be more in the future when Grunt 1.0 is released. This plugin is used by a **lot** of grunt projects (443,282 downloads in the last month), so it would be nice if someone stepped up. Happy to add multiple people.

**Comment by slinto** [comment]
Hi,
I'll be glad when I can maintain this repository. 
This may be my first 'not mine' repository which I maintain.
Thx.

**Comment by adrianlee44** [comment]
Hi,

I have used this for multiple projects of mine and would love to happy out if you are looking for a maintainer.

Thanks,

**Comment by sindresorhus** [comment]
Thanks for offering @slinto @adrianlee44 ❤️ Added you both.

If you need a place to start, maybe triage some issues.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated because Grunt is no longer actively maintained, so it doesn't make sense for me to maintain this project either.
