### ISSUE TITLE
Abstracted grunt hooks package

### ISSUE THREAD

**Issue by TheSavior** [sindresorhus/time-grunt#81]
I needed to do something similar to this plugin where it hooks into grunt's tasks. I pulled out the code for the grunt hooks from this package into another package and wrote tests(!): https://github.com/TheSavior/grunt-before-after-hooks

Would you guys be open to a PR refactoring this module on top of that to not have duplicated code doing this? I'm more than happy to add all of the contributors to this repo to the other one.

**Comment by sindresorhus** [comment]
Looks good, but this module is done. I'm not interested in potential regressions just to abstract some code out. Your module is missing the attribution required by the MIT license.

**Comment by TheSavior** [comment]
Sounds reasonable. 

Thanks for the catch on the license. The generator we use from work auto sets Apache-2. Fixed

**Comment by sindresorhus** [comment]
@TheSavior You didn't have to switch to MIT. MIT is Apache-2 compatible. You just have to mention the other copyright holders in the license file. Example: https://github.com/sindresorhus/to-fast-properties/blob/f65cab875234f8a9ee9b28df5d4db5c4a92fd0d9/license#L3-L4

**Comment by sindresorhus** [comment]
@TheSavior Happy to mention your module in a `Related` section at the bottom though, if you do a pull request. See example: https://github.com/sindresorhus/cocoa-dialog#related
