### ISSUE TITLE
Not outputting total elapsed time unless grunt is called with `--no-color` option

### ISSUE THREAD

**Issue by goibon** [sindresorhus/time-grunt#84]
I'm having an issue where `time-grunt` does not output the total elapsed time but only outputs the time for each separate task as shown in the image below. I randomly noticed this because I tried running grunt from Sublime Text 3 rather than PowerShell and in the ST3 console the total elapsed time was correctly displayed. After fiddling with it a little I found out that I can make it appear in PowerShell if I call grunt with the `--no-color` option.
I know that this may not be an issue with `time-grunt` but rather with PowerShell but I thought I'd ask here to hear if you have any idea what might cause this.

![time-grunt-builddeploy](https://cloud.githubusercontent.com/assets/2376777/18463931/f5d5e76c-798d-11e6-86ca-b17006a4e7cc.PNG)

**Comment by sindresorhus** [comment]
Node.js used to have some problems with console output being cut off right before the process exited. Ensure you're on the latest Node.js version.

**Comment by goibon** [comment]
I am currently using Node.js v. 6.6.0 which should be latest at the time of writing

**Comment by kevva** [comment]
Have you made sure that the time isn't written in the same color as the background? I'm asking because I see there are two newlines between the output and the prompt.

**Comment by goibon** [comment]
@kevva I had thought about it since "--no-color" solved it, but apparently I had only tested with other colors that hid it as well.. I finally found a color where I could read the total time, but then I'm having trouble with reading the output from my other grunt tasks. Is there any way I can set the colors that `time-grunt` uses somehow?

**Comment by sindresorhus** [comment]
`time-grunt` is just using the `magenta` color to show the total time. It's up to your terminal/theme how to render it. Not gonna add options for the color. Closing as it's not an issue with `time-grunt`.
