### ISSUE TITLE
grunt-contrib-watch option 'spawn': false blocks time-grunt?

### ISSUE THREAD

**Issue by louiswalch** [sindresorhus/time-grunt#90]
I was testing setting this value to false because it supposedly speeds up the build a bit, but time-grunt doesn't seem to display after my watch task is complete. Any ideas?

https://github.com/gruntjs/grunt-contrib-watch#optionsspawn

**Comment by sindresorhus** [comment]
Closing as this project is deprecated because Grunt is no longer actively maintained, so it doesn't make sense for me to maintain this project either.
